import React from 'react';
import { Inter } from 'next/font/google';

import StyledComponentsRegistry from '../lib/AntdRegistry';

// import '@/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => (
  React.createElement('html', { lang: 'en' },
    React.createElement('body', { className: inter.className },
      React.createElement(StyledComponentsRegistry, null, children)
    )
  )
);

export default RootLayout;
